# Generated by Django 3.2.11 on 2022-01-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('purchaseId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=500)),
                ('purchaseDate', models.DateField()),
                ('supplier', models.CharField(max_length=500)),
                ('productQuantity', models.IntegerField()),
                ('costPerUnit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchaseAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
